@@ -12,6 +12,7 @@ jobs:

        uses: actions/setup-python@v3

        with:

          python-version: "3.10"

          cache: "pip"

      - name: Install Python lint libraries

        run: |

          نقطة تثبيت autoflake isort الأسود
